import 'package:flutter/material.dart';
const List<Color> colors = [
  Colors.red,
  Colors.pink,
  Colors.purple,
  Colors.deepPurple,
  Colors.indigo,
  Colors.blue,
  Colors.lightBlue,
  Colors.cyan,
  Colors.teal,
  Colors.green,
  Colors.lightGreen,
  Colors.lime,
  Colors.yellow,
  Colors.amber,
  Colors.orange,
  Colors.deepOrange,
  Colors.brown,
  Colors.grey,
  Colors.black,
  Colors.white,
];
const List<String> colorNames = [
  "red",
  "pink",
  "purple",
  "deep purple",
  "indigo",
  "blue",
  "light blue",
  "cyan",
  "teal",
  "green",
  "light green",
  "lime",
  "yellow",
  "amber",
  "orange",
  "deep orange",
  "brown",
  "grey",
  "black",
  "white",
  ""
];

